#!/bin/bash
# @FershoUno

echo -n "	THASH v.2.0
	CODED: @FershoUno
Ingrese tu texto: "
read text

ListHash=(md5sum sha1sum sha224sum sha256sum sha384sum sha512sum)

for i in "${ListHash[@]}"
do
echo "
$i      : `echo $text| $i | cut -d " " -f 1`
$i"inv"   : `echo $text| $i | cut -d " " -f 1| rev`"
done
